# Generated by Django 4.2.1 on 2023-08-09 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_online_shop', '0003_onlineshop_image'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='onlineshop',
            table='advertisement',
        ),
    ]
