# Generated by Django 4.2.1 on 2023-08-20 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_online_shop', '0005_alter_onlineshop_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onlineshop',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
